### ISSUE TITLE
Tone Mapping and Checkpoints

### ISSUE THREAD

**Issue by orzanai** [Galaxies99/DeepHDR-pytorch#8]
Hi, thank you for your effort and this great work!

I have some questions about tone mapping and checkpoints.
Do you think we can implement a tone mapping function for this model to automize post process instead of using another application?

Additionally, I trained model for 50 epoch and model have not been saving any checkpoint until now. I'm working on Google Colab so, if there is a way that making possible to get more checkpoints it would be great.

If do you have any idea about this questions, I'd be happy to hear that for further development.
Thanks in advance!

**Comment by Galaxies99** [comment]
Hi, thank you for your interest in our re-implementation of the DeepHDR!

We are not the original authors of the paper, and thus we only follow the paper to implement the method in pytorch.

I think the tone-mapping function can be added in the model, if the downstream applications is fixed. Otherwise I think it might be better to let the users to choose the type of tone-mapping methods according to their downstream applications.

Also, I think the train code is saving the checkpoints (see L141-142 of train.py). I would suggest you to check that whether `configs.checkpoint_dir` is correctly set, since it might not exist especially in CoLab environment.

**Comment by orzanai** [comment]
> Hi, thank you for your interest in our re-implementation of the DeepHDR!
> 
> We are not the original authors of the paper, and thus we only follow the paper to implement the method in pytorch.
> 
> I think the tone-mapping function can be added in the model, if the downstream applications is fixed. Otherwise I think it might be better to let the users to choose the type of tone-mapping methods according to their downstream applications.
> 
> Also, I think the train code is saving the checkpoints (see L141-142 of train.py). I would suggest you to check that whether `configs.checkpoint_dir` is correctly set, since it might not exist especially in CoLab environment.

Thank you so much for your fast answer, much appreciated!
